# Generated by Django 6.0.4 on 2026-04-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="branch",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="college",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="github",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="year",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="skills",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
