# Generated by Django 6.0.4 on 2026-04-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_skill_remove_user_skills_user_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="skills",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
